#!/usr/bin/env python3
from pathlib import Path
import shutil
import subprocess

IN_DIR = Path("site")
OUT_DIR = Path("build")

CHEF = "./chef"

VARS = [
    "-d", "NAME", "beauconstrictor",
    "-d", "EMAIL", "beauconstrictor@tilde.team",
    "-d", "ROOT", "/~beauconstrictor",
]

HOSTNAME = "tilde.team"

ROOT = Path("/~beauconstrictor")

def run_chef(fmt: str, out: Path, src: Path, online_path: Path):
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [CHEF, *VARS, "-H", HOSTNAME, "-O", str(online_path), "-f", fmt, "-o", str(out), str(src)],
        check=True
    )

gophermap_msg = "1Go to the index\tindex"

def main():
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)

    (OUT_DIR / "gopher").mkdir(parents=True, exist_ok=True)
    with open(str(OUT_DIR / "gopher" / "gophermap"), "w") as f:
        f.write(gophermap_msg)

    for path in IN_DIR.rglob("*"):
        rel = path.relative_to(IN_DIR)

        if path.is_dir():
            (OUT_DIR / "html" / rel).mkdir(parents=True, exist_ok=True)
            (OUT_DIR / "gemini" / rel).mkdir(parents=True, exist_ok=True)
            (OUT_DIR / "gopher" / rel).mkdir(parents=True, exist_ok=True)
            with open(str(OUT_DIR / "gopher" / rel / "gophermap"), "w") as f:
                f.write(gophermap_msg)
            continue

        # Compute output paths
        out_rel = rel.as_posix()

        # .gmi to .html
        html_rel = out_rel
        if html_rel.endswith(".gmi"):
            html_rel = html_rel[:-4] + ".html"

        # .gmi to 
        gopher_rel = out_rel
        if gopher_rel.endswith(".gmi"):
            gopher_rel = gopher_rel[:-4]

        html_out = OUT_DIR / "html" / html_rel
        gem_out = OUT_DIR / "gemini" / out_rel
        gopher_out = OUT_DIR / "gopher" / gopher_rel

        print(f"{path} -> {html_rel}")

        run_chef("html", html_out, path, ROOT / rel)
        run_chef("gemini", gem_out, path, ROOT / rel)
        run_chef("gopher", gopher_out, path, ROOT / rel)


if __name__ == "__main__":
    main()
