#!/usr/bin/env python3

# chef - A gemtext -> HTML/gemini/gopher processor

from urllib.parse import urlparse
from typing import TextIO
from pathlib import Path
import argparse

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="chef",
        description="A gemtext -> HTML/gemini/gopher processor",
        epilog="The template can access vars defined with -d using "
            "the $(var) syntax. The CONTENT and TITLE variables are "
            "predefined."
    )

    parser.add_argument("gemtext")
    parser.add_argument("-o", "--outfile", required=True)
    parser.add_argument("-f", "--format", required=True)
    parser.add_argument("-t", "--template", default="template.html")
    parser.add_argument("-d", "--define", nargs=2, action="append")
    parser.add_argument("-w", "--wrap", default=80, type=int)
    parser.add_argument("-H", "--hostname", required=True)
    parser.add_argument("-O", "--online_path", required=True)

    return parser.parse_args()

def wrap(s: str, w: int) -> list[str]:
    words = s.split()
    lines = []
    line = ""

    for word in words:
        if len(line) + len(word) + (1 if line else 0) <= w:
            line += (" " if line else "") + word
        else:
            lines.append(line)
            line = word

    if line:
        lines.append(line)

    return lines

def tohtml(gem: str) -> (str, str):
    preformatted = False
    in_list = False
    html_parts = []
    title = None

    for l in gem.split("\n"):
        if l.startswith("```") and not preformatted:
            preformatted = True
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append("<pre>")
            continue
        if l == "```" and preformatted:
            preformatted = False
            html_parts.append("</pre>")
            continue

        if preformatted:
            html_parts.append(l + "\n")
            continue

        if l.startswith("* "):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{l[2:]}</li>")
            continue

        if in_list:
            html_parts.append("</ul>")
            in_list = False

        if l.startswith("### "):
            html_parts.append(f"<h3>{l[4:]}</h3>")
        elif l.startswith("## "):
            html_parts.append(f"<h2>{l[3:]}</h2>")
        elif l.startswith("# "):
            if title == None: title = l[2:]
            html_parts.append(f"<h1>{l[2:]}</h1>")

        elif l.startswith("=> "):
            parts = l[3:].split(" ")
            if len(parts) == 0: continue
            url = parts[0]
            if not "://" in url and url.endswith(".gmi"):
                url = url[:-4] + ".html"
            text = " ".join(parts[1:]) if len(parts) > 1 else url
            html_parts.append(f"<a href=\"{url}\">{text}</a>")

        elif l.strip() == "":
            continue
        else:
            html_parts.append(f"<p>{l}</p>")

    if in_list:
        html_parts.append("</ul>")

    return "".join(html_parts), title or "Untitled"

def add_heading(output: list[str], l: str, border: str, prefix: str, width: int) -> None:
    lines = wrap(l[len(prefix):], width)
    llen  = max([len(i) for i in lines])
    output.append("i" + border * llen)
    for line in lines:
        output.append("i" + line)
    output.append("i" + border * llen)

def add_gopher_link(output: list[str], l: str, width: int, hostname: str, path: str) -> None:
    parts = l[3:].split(" ")
    if len(parts) == 0: return
    url  = parts[0]
    name = wrap(" ".join(parts[1:]), width)

    if url.startswith("https://"):
        for name_l in name:
            parsed = urlparse(url)
            s = f"h{name_l}\t{parsed.path}\t{parsed.hostname}"
            if parsed.port: s += f"\t{parsed.port}"
            output.append(s)
    elif url.startswith("gopher://"):
        output.append("iTODO: implement gopher links from gopher")
    elif url.startswith("gemini://"):
        output.append("iTODO: implement gemini links from gopher")
    elif url.endswith(".gmi"):
        selector = Path(url[:-4]).relative_to(path)
        for name_l in name:
            output.append(f"1{name_l}\t{selector}\t{hostname}\t70")
    # TODO: support .txt files
    else:
        selector = Path(url).relative_to(path)
        for name_l in name:
            output.append(f"9{name_l}\t{selector}{hostname}\t70")

def format_html(source: str, args: argparse.Namespace) -> str:
    with open(args.template, "r", encoding="utf-8") as f:
        output = f.read()

    content, title = tohtml(source)
    output = output.replace("$(TITLE)", title)
    output = output.replace("$(CONTENT)", content)
    return output

def format_gemtext(source: str, args: argparse.Namespace) -> str:
    return source

def format_gopher(source: str, args: argparse.Namespace) -> str:
    output = []

    preformatted = False

    for l in source.split("\n"):
        if l.startswith("```"):
            preformatted = not preformatted
            continue
        if preformatted:
            output.append("i" + l)
            continue

        if l.startswith("# "):
            add_heading(output, l, "=", "# ", args.wrap)
        elif l.startswith("## "):
            add_heading(output, l, "-", "## ", args.wrap)
        elif l.startswith("###"):
            add_heading(output, l, ".", "### ", args.wrap)

        elif l.startswith("=> "):
            add_gopher_link(output, l, args.wrap, args.hostname, Path(args.online_path).parent)

        elif l == "":
            output.append("i")
        else:
            lines = wrap(l, args.wrap)
            for line in lines:
                output.append("i" + line)

    return "\n".join(output) + "\n"

def main() -> None:
    args = parse_args()

    with open(args.gemtext, "r", encoding="utf-8") as gem:
        source = gem.read()

    output = ""
    match args.format:
        case "html":      output = format_html  (source, args)
        case "gemini":    output = format_gemini(source, args)
        case "gophermap": output = format_gopher(source, args)

    for k,v in args.define:
        output = output.replace(f"$({k})", v)

    with open(args.outfile, "w", encoding="utf-8") as out:
        out.write(output)

if __name__ == "__main__":
    main()
