#!/usr/bin/env python3

# chef - A gemtext -> HTML template processor

from typing import TextIO
from pathlib import Path
import argparse

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="chef",
        description="A gemtext -> HTML template processor",
        epilog="The template can access vars defined with -d using "
            "the $(var) syntax. The CONTENT and TITLE variables are "
            "predefined."
    )

    parser.add_argument("gemtext")
    parser.add_argument("-o", "--outfile", required=True)
    parser.add_argument("-f", "--format", required=True)
    parser.add_argument("-t", "--template", default="template.html")
    parser.add_argument("-d", "--define", nargs=2, action="append")
    parser.add_argument("-w", "--wrap", default=80, type=int)
    parser.add_argument("-g", "--gophernicus", action="store_true")

    return parser.parse_args()

def wrap(s: str, w: int) -> list[str]:
    words = s.split()
    lines = []
    line = ""

    for word in words:
        if len(line) + len(word) + (1 if line else 0) <= w:
            line += (" " if line else "") + word
        else:
            lines.append(line)
            line = word

    if line:
        lines.append(line)

   return lines

def tohtml(gem: str) -> (str, str):
    preformatted = False
    in_list = False
    html_parts = []
    title = None

    for l in gem.split("\n"):
        if l.startswith("```") and not preformatted:
            preformatted = True
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append("<pre>")
            continue
        if l == "```" and preformatted:
            preformatted = False
            html_parts.append("</pre>")
            continue

        if preformatted:
            html_parts.append(l + "\n")
            continue

        if l.startswith("* "):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{l[2:]}</li>")
            continue

        if in_list:
            html_parts.append("</ul>")
            in_list = False

        if l.startswith("### "):
            html_parts.append(f"<h3>{l[4:]}</h3>")
        elif l.startswith("## "):
            html_parts.append(f"<h2>{l[3:]}</h2>")
        elif l.startswith("# "):
            if title == None: title = l[2:]
            html_parts.append(f"<h1>{l[2:]}</h1>")

        elif l.startswith("=> "):
            parts = l[3:].split(" ")
            if len(parts) == 0: continue
            url = parts[0]
            if not "://" in url and url.endswith(".gmi"):
                url = url[:-4] + ".html"
            text = " ".join(parts[1:]) if len(parts) > 1 else url
            html_parts.append(f"<a href=\"{url}\">{text}</a>")

        elif l.strip() == "":
            continue
        else:
            html_parts.append(f"<p>{l}</p>")

    if in_list:
        html_parts.append("</ul>")

    return "".join(html_parts), title or "Untitled"

def add_heading(output: list[str], l: str, border: str, prefix: str, width: int, gophernicus: bool) -> None:
    lines = wrap(l[len(prefix):], width)
    llen  = max([len(i) for i in lines])
    text_mode = "" if gophernicus else ""
    output.append(text_mode + border * llen)
    for line in lines:
        output.append(text_mode + line)
    output.append(text_mode + border * llen)

def add_gopher_link(output: list[str], l: str, width: int, gophernicus: bool) -> None:
    parts = l[3:].split(" ")
    if len(parts) == 0: return
    url  = parts[0]
    name = wrap(" ".join(parts[1:]), width)

    if url.startswith("https://") or url.startswith("mailto:"):
        for name_l in name:
            output.append(f"\th{name_l}\t{url}\t_\t_")
    elif url.endswith(".gmi"):
        selector = url[:-4]
        for name_l in name:
            output.append(f"\t1{name_l}\t{selector}")
    # TODO: support .txt files
    else:
        for name_l in name:
            output.append(f"\t9{name_l}\t{url}")

def format_html(source: str, args: argparse.Namespace) -> str:
    with open(args.template, "r", encoding="utf-8") as f:
        output = f.read()

    content, title = tohtml(source)
    output = output.replace("$(TITLE)", title)
    output = output.replace("$(CONTENT)", content)
    return output

def format_gemtext(source: str, args: argparse.Namespace) -> str:
    return source

def format_gopher(source: str, args: argparse.Namespace, gophernicus: bool) -> str:
    output = []

    text_mode = "" if gophernicus else "i"
    title = None

    for l in source.split("\n"):
        preformatted = False
        if l.startswith("```"):
            preformatted = not preformatted
            continue
        if preformatted:
            output.append(text_mode + l)
            continue

        if l.startswith("# "):
            if title == None: title = l[2:]
            add_heading(output, l, "=", "# ", args.wrap, gophernicus)
        elif l.startswith("## "):
            add_heading(output, l, "-", "## ", args.wrap, gophernicus)
        elif l.startswith("###"):
            add_heading(output, l, ".", "### ", args.wrap, gophernicus)

        elif l.startswith("=> "):
            add_gopher_link(output, l, args.wrap, gophernicus)

        elif l == "":
            output.append(text_mode)
        else:
            lines = wrap(l, args.wrap)
            for line in lines:
                output.append(text_mode + line)

    output = ["!" + title or "Untitled"] + output

    return "\n".join(output) + "\n"

def main() -> None:
    args = parse_args()

    with open(args.gemtext, "r", encoding="utf-8") as gem:
        source = gem.read()

    output = ""
    match args.format:
        case "html":   output = format_html  (source, args)
        case "gemini": output = format_gemini(source, args)
        case "gophermap":
            if args.gophernicus and Path(args.outfile).name == "index":
                output = format_gopher(source, args, True)
            else:
                output = format_gopher(source, args, False)

    for k,v in args.define:
        output = output.replace(f"$({k})", v)

    outfile = args.outfile
    if args.format == "gophermap" and args.gophernicus:
        path = Path(outfile)
        if path.name == "index":
            outfile = str(path.with_name("gophermap"))
            output = "\n".join(["\t" + l for l in output.split("\n")])

    with open(outfile, "w", encoding="utf-8") as out:
        out.write(output)

if __name__ == "__main__":
    main()

